= Digital Modernization

== Monitoring the Application

****
*Expected Outcome:*

* Add and understand Docker Healthchecks to the Pet Store Docker artifacts
* Add and understand Container Healthchecks to Fargate
* Ship container logs for to CloudWatch

*Lab Requirements:*
* an Amazon Elastic Container Service Cluster
* an Amazon Elastic Container Service for Kubernetes Cluster

*Average Lab Time:* 
30-45 minutes
****

=== Introduction
When it comes to monitoring an application, a key concept to understand is you need to ensure that the application is working rather than only looking to see if server or container is running. In this module, we will go over some key concepts in monitoring and logging and how to integrate those concepts with our Pet Store application.

==== Docker Healthchecks

The `HEALTHCHECK` instruction tells Docker how to test a container to check that it is still working. This can detect cases such as a web server that is stuck in an infinite loop and unable to handle new connections, even though the server process is still running. When a container has a healthcheck specified, it has a health status in addition to its normal status. This status is initially starting. Whenever a health check passes, it becomes `healthy` (whatever state it was previously in). After a certain number of consecutive failures, it becomes `unhealthy`.

1. To get started, navigate to the folder where you created your `Dockerfile` in the `containerize-application` folder from the previous lab within this repository. Then open the `Dockerfile` in your editor of choice.
+
2. At the bottom of our `Dockerfile` we will add a `HEALTHCHECK` that tests our application server. Add the `HEALTHCHECK` between the `ENTRYPOINT` command in the `Dockerfile` like the example below:
+
[source,shell]
----
# run the application
ENTRYPOINT [ "/opt/jboss/docker-entrypoint.sh" ]
# add a Healthcheck
HEALTHCHECK --interval=30s --timeout=5s --retries=5 --start-period=30s CMD curl --fail http://127.0.0.1:8080/applicationPetstore || exit 1
CMD [ "-b", "0.0.0.0", "-bmanagement", "0.0.0.0" ]
----
+
- To review the above comand we will go over some of the flags. The options that can appear before `CMD` in a `HEALTHCHECK` are:
* `--interval=DURATION` (default: `30s`)
* `--timeout=DURATION` (default: `30s`)
* `--retries=N` (default: `3`)
* `--start-period=DURATION` (default: `0s`)
- You will notice the `CMD curl --fail http://127.0.0.1:8080/applicationPetstore || exit 1` in our `HEALTHCHECK`. This is how we are testing that the application is running. The commands exit status indicates the health status of  the container. The possible values are:
* 0: success - the container is healthy and ready for use
* 1: unhealthy - the container is not working correctly
* 2: reserved - do not use this exit code
+
3. Save the `Dockerfile` and move on to the next section. There is a working `Dockerfile` in the `monitor-application/container` folder within this repository if you need a full example.

==== Healthchecks in Docker Compose
As a refresher, Docker Compose is a tool for defining and running multi-container Docker applications. With Compose, you use a YAML file to configure your application’s services. Then, with a single command, you create and start all the services from your configuration.

Using Compose is basically a three-step process:

* Define your app’s environment with a `Dockerfile` so it can be reproduced anywhere.
* Define the services that make up your app in `docker-compose.yml` so they can be run together in an isolated environment.
* Run `docker-compose` up and Compose starts and runs your entire app.

1. To get started, navigate to the folder where you created your `docker-compose.yml` in the `containerize-application` folder from the previous lab within this repository. Then open the `docker-compose.yml` in your editor of choice.
+
2. Similar to the previous section, we are going to add healthchecks but this time we will also add one for our postgres container. 
+
3. Add the `healthcheck` section to `postgres` so that it looks like the example below. For our healthecheck, we are going to add a simple `CMD-SHELL` command to issue the `pg_isready` utility for checking the connection status to PostgreSQL. Since we are using the official PostgreSQL image available from Docker Hub the `pg_isready` command should be available within our container.
+
[source,yaml]
----
version: '3.4'

services:

  postgres:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_DB=petstore'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=password'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
----
+
4. For the Pet Store application add the following `healthcheck` section to `petstore` so that it looks like the example below. For our healthcheck, we are simply mirroring what was already defined in the `Dockerfile` earlier.
+
[source,yaml]
----
  petstore:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 8080:8080
      - 9990:9990
    environment:
      - 'DB_URL=jdbc:postgresql://postgres:5432/petstore?ApplicationName=applicationPetstore'
      - 'DB_HOST=postgres'
      - 'DB_PORT=5432'
      - 'DB_NAME=petstore'
      - 'DB_USER=admin'
      - 'DB_PASS=password'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/applicationPetstore"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
----
+
5. Save the `docker-compose.yml` and move on to the next section. There is a working `docker-compose.yml` in the `monitor-application/container` folder within this repository if you need a full example.

==== Testing the Healthchecks

TO DO: 

==== Updating and Deploying Task Definition to Fargate

TO DO:

==== Shipping and Viewing Logs

TO DO: 
